// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"6qialdt9z7","name":"transactionsCRUD","description":"","endpoint":"https://6qialdt9z7.execute-api.us-west-2.amazonaws.com/Development","region":"us-west-2","paths":["/transactions","/transactions/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:5c0b0859-88c1-4d49-bee6-77a8bc7ae399',
    'aws_cognito_region': 'us-west-2',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '7e723139c5d64b50b95e812a7ca64d6e',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f5536f16-fcdc-4ce3-9982-6299f7908273',
    'aws_project_name': 'IEEESSMMS',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'ieeessmms-mobilehub-2131448227',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_PUGwGAxxh',
    'aws_user_pools_web_client_id': '1um0b2of4r1l5hht32onh2b7q2',
}

export default awsmobile;
