// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"6qialdt9z7","name":"transactionsCRUD","description":"","endpoint":"https://6qialdt9z7.execute-api.us-west-2.amazonaws.com/Development","region":"us-west-2","paths":["/transactions","/transactions/123"]}],
    'aws_cognito_identity_pool_id': 'us-west-2:16a723f8-4b00-4437-b485-e95411176fbe',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsamplifyvue-hosting-mobilehub-1144753982',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd147sg2tmosbt0.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-west-2',
    'aws_dynamodb_table_schemas': [{"tableName":"awsamplifyvue-mobilehub-1144753982-transactions","attributes":[{"name":"userId","type":"S"},{"name":"date","type":"S"},{"name":"amount","type":"N"},{"name":"balance","type":"N"}],"indexes":[],"region":"us-west-2","hashKey":"userId","rangeKey":"date"}],
    'aws_mobile_analytics_app_id': 'b6a3ca9f779d42fab806ffebe93eaeab',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '14ae44d6-85ad-434c-88d6-d63df0c5645a',
    'aws_project_name': 'aws-amplify-vue-2018-05-20-19-25-58',
    'aws_project_region': 'us-west-2',
    'aws_resource_bucket_name': 'awsamplifyvue-deployments-mobilehub-1144753982',
    'aws_resource_name_prefix': 'awsamplifyvue-mobilehub-1144753982',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'awsamplifyvue-userfiles-mobilehub-1144753982',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_3cTwZqVgu',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '13udabii5a0led3hrckbp0d3je',
}

export default awsmobile;
